
export const REQUEST_TO_ADD = "REQUEST_TO_ADD"
export type REQUEST_TO_ADD = typeof REQUEST_TO_ADD

export const REQUEST_TO_EDIT = "REQUEST_TO_EDIT"
export type REQUEST_TO_EDIT = typeof REQUEST_TO_EDIT

export const REQUEST_COMMIT_EDIT = "REQUEST_COMMIT_EDIT"
export type REQUEST_COMMIT_EDIT = typeof REQUEST_COMMIT_EDIT


export const REQUEST_TO_REMOVE = "REQUEST_TO_REMOVE"
export type REQUEST_TO_REMOVE = typeof REQUEST_TO_REMOVE

export const REQUEST_TO_TOGGLE = "REQUEST_TO_TOGGLE"
export type REQUEST_TO_TOGGLE = typeof REQUEST_TO_TOGGLE

export const REQUEST_TO_RESET = "REQUEST_TO_RESET"
export type REQUEST_TO_RESET = typeof REQUEST_TO_RESET
