
export const REQUEST_TO_ADD = "REQUEST_TO_ADD"
export type REQUEST_TO_ADD = typeof REQUEST_TO_ADD

export const REQUEST_TO_REMOVE = "REQUEST_TO_REMOVE"
export type REQUEST_TO_REMOVE = typeof REQUEST_TO_REMOVE

export const REQUEST_TO_TOGGLE = "REQUEST_TO_TOGGLE"
export type REQUEST_TO_TOGGLE = typeof REQUEST_TO_TOGGLE

export const REQUEST_TO_RESET = "REQUEST_TO_RESET"
export type REQUEST_TO_RESET = typeof REQUEST_TO_RESET
